# build container
FROM node:current-alpine as builder

## Install git toolchain to enable turborepo
RUN apk add --no-cache git

WORKDIR /usr/src/app
COPY . .

RUN npm install
RUN npm run build:web

# runtime
FROM nginx:latest

COPY --from=builder /usr/src/app/apps/ui/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY deploy/etc/nginx/conf.d/ui.conf /etc/nginx/conf.d
